apiVersion: batch/v1
kind: Job
metadata:
  name: {NAME}
  labels:
    kueue.x-k8s.io/queue-name: farai
    wandb-group: {WANDB_GROUP}
    wandb-project: {WANDB_PROJECT}
    wandb-job-name: {WANDB_JOB_NAME}
    wandb-entity: {WANDB_ENTITY}
    launch-id: {LAUNCH_ID}
spec:
  suspend: true
  template:
    metadata:
      generateName: {NAME}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      priorityClassName: interactive
      volumes:
      - name: training
        persistentVolumeClaim:
          claimName: lp-training-storage
      containers:
      - name: devbox-container
        image: "{CONTAINER}"
        command:
          - bash
          - -c
          - |
            git pull; git checkout {COMMIT_HASH}; git submodule update --recursive; {COMMAND}
        resources:
          requests:
            cpu: {CPU}
            memory: {MEMORY}
          limits:
            nvidia.com/gpu: {GPU}
        env:
        - name: OMP_NUM_THREADS
          value: {OMP_NUM_THREADS}
        - name: GIT_ASKPASS
          value: "true"
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: github-credentials
              key: pat
        - name: GIT_CONFIG_PARAMETERS
          value: "'credential.https://github.com.username=$(GITHUB_PAT)'"
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb
              key: api-key
        - name: WANDB_ENTITY
          value: {WANDB_ENTITY}
        - name: WANDB_JOB_NAME
          value: {WANDB_JOB_NAME}
        - name: WANDB_PROJECT
          value: {WANDB_PROJECT}
        - name: WANDB_GROUP
          value: {WANDB_GROUP}
        volumeMounts:
        - name: training
          mountPath: {TRAINING_MOUNT}
      restartPolicy: Never
      imagePullSecrets:
      - name: docker